[package]
name = "reckless-cs-burn"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
burn = { package = "burn-core", version = "0.21.0", default-features = false, features = ["std"] }
burn-flex = { version = "0.21.0", default-features = false, features = ["std"] }
burn-nn = { version = "0.21.0", default-features = false, features = ["std"] }
burn-store = "0.21.0"
serde_json = "1.0"
